package com.jsy.cn.dao;

import org.springframework.stereotype.Repository;

import com.jsy.cn.entity.Staff;

public interface StaffMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TSTAFF
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TSTAFF
     *
     * @mbggenerated
     */
    int insert(Staff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TSTAFF
     *
     * @mbggenerated
     */
    int insertSelective(Staff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TSTAFF
     *
     * @mbggenerated
     */
    Staff selectByPrimaryKey(Long pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TSTAFF
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Staff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TSTAFF
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Staff record);
}