package com.jsy.cn.entity;

import java.util.Date;

public class Staff {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTAFF.PKID
     *
     * @mbggenerated
     */
    private Long pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTAFF.STAFF_NAME
     *
     * @mbggenerated
     */
    private String staffName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTAFF.MOBILE
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTAFF.CODE
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTAFF.PASSWORD
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTAFF.USER_SOURCE
     *
     * @mbggenerated
     */
    private Long userSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTAFF.ID_CARD
     *
     * @mbggenerated
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTAFF.EMAIL
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTAFF.STATUS
     *
     * @mbggenerated
     */
    private Long status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTAFF.ADDED_BY
     *
     * @mbggenerated
     */
    private Long addedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTAFF.ADDED_BY_NAME
     *
     * @mbggenerated
     */
    private String addedByName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTAFF.ADDED_TIME
     *
     * @mbggenerated
     */
    private Date addedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTAFF.LAST_MODIFIED_BY
     *
     * @mbggenerated
     */
    private Long lastModifiedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTAFF.LAST_MODIFIED_BY_NAME
     *
     * @mbggenerated
     */
    private String lastModifiedByName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTAFF.LAST_MODIFIED_TIME
     *
     * @mbggenerated
     */
    private Date lastModifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTAFF.LAST_MODIFIED_IP
     *
     * @mbggenerated
     */
    private String lastModifiedIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTAFF.VALID
     *
     * @mbggenerated
     */
    private String valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSTAFF.PKID
     *
     * @return the value of TSTAFF.PKID
     *
     * @mbggenerated
     */
    public Long getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSTAFF.PKID
     *
     * @param pkid the value for TSTAFF.PKID
     *
     * @mbggenerated
     */
    public void setPkid(Long pkid) {
        this.pkid = pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSTAFF.STAFF_NAME
     *
     * @return the value of TSTAFF.STAFF_NAME
     *
     * @mbggenerated
     */
    public String getStaffName() {
        return staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSTAFF.STAFF_NAME
     *
     * @param staffName the value for TSTAFF.STAFF_NAME
     *
     * @mbggenerated
     */
    public void setStaffName(String staffName) {
        this.staffName = staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSTAFF.MOBILE
     *
     * @return the value of TSTAFF.MOBILE
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSTAFF.MOBILE
     *
     * @param mobile the value for TSTAFF.MOBILE
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSTAFF.CODE
     *
     * @return the value of TSTAFF.CODE
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSTAFF.CODE
     *
     * @param code the value for TSTAFF.CODE
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSTAFF.PASSWORD
     *
     * @return the value of TSTAFF.PASSWORD
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSTAFF.PASSWORD
     *
     * @param password the value for TSTAFF.PASSWORD
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSTAFF.USER_SOURCE
     *
     * @return the value of TSTAFF.USER_SOURCE
     *
     * @mbggenerated
     */
    public Long getUserSource() {
        return userSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSTAFF.USER_SOURCE
     *
     * @param userSource the value for TSTAFF.USER_SOURCE
     *
     * @mbggenerated
     */
    public void setUserSource(Long userSource) {
        this.userSource = userSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSTAFF.ID_CARD
     *
     * @return the value of TSTAFF.ID_CARD
     *
     * @mbggenerated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSTAFF.ID_CARD
     *
     * @param idCard the value for TSTAFF.ID_CARD
     *
     * @mbggenerated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSTAFF.EMAIL
     *
     * @return the value of TSTAFF.EMAIL
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSTAFF.EMAIL
     *
     * @param email the value for TSTAFF.EMAIL
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSTAFF.STATUS
     *
     * @return the value of TSTAFF.STATUS
     *
     * @mbggenerated
     */
    public Long getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSTAFF.STATUS
     *
     * @param status the value for TSTAFF.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Long status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSTAFF.ADDED_BY
     *
     * @return the value of TSTAFF.ADDED_BY
     *
     * @mbggenerated
     */
    public Long getAddedBy() {
        return addedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSTAFF.ADDED_BY
     *
     * @param addedBy the value for TSTAFF.ADDED_BY
     *
     * @mbggenerated
     */
    public void setAddedBy(Long addedBy) {
        this.addedBy = addedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSTAFF.ADDED_BY_NAME
     *
     * @return the value of TSTAFF.ADDED_BY_NAME
     *
     * @mbggenerated
     */
    public String getAddedByName() {
        return addedByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSTAFF.ADDED_BY_NAME
     *
     * @param addedByName the value for TSTAFF.ADDED_BY_NAME
     *
     * @mbggenerated
     */
    public void setAddedByName(String addedByName) {
        this.addedByName = addedByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSTAFF.ADDED_TIME
     *
     * @return the value of TSTAFF.ADDED_TIME
     *
     * @mbggenerated
     */
    public Date getAddedTime() {
        return addedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSTAFF.ADDED_TIME
     *
     * @param addedTime the value for TSTAFF.ADDED_TIME
     *
     * @mbggenerated
     */
    public void setAddedTime(Date addedTime) {
        this.addedTime = addedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSTAFF.LAST_MODIFIED_BY
     *
     * @return the value of TSTAFF.LAST_MODIFIED_BY
     *
     * @mbggenerated
     */
    public Long getLastModifiedBy() {
        return lastModifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSTAFF.LAST_MODIFIED_BY
     *
     * @param lastModifiedBy the value for TSTAFF.LAST_MODIFIED_BY
     *
     * @mbggenerated
     */
    public void setLastModifiedBy(Long lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSTAFF.LAST_MODIFIED_BY_NAME
     *
     * @return the value of TSTAFF.LAST_MODIFIED_BY_NAME
     *
     * @mbggenerated
     */
    public String getLastModifiedByName() {
        return lastModifiedByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSTAFF.LAST_MODIFIED_BY_NAME
     *
     * @param lastModifiedByName the value for TSTAFF.LAST_MODIFIED_BY_NAME
     *
     * @mbggenerated
     */
    public void setLastModifiedByName(String lastModifiedByName) {
        this.lastModifiedByName = lastModifiedByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSTAFF.LAST_MODIFIED_TIME
     *
     * @return the value of TSTAFF.LAST_MODIFIED_TIME
     *
     * @mbggenerated
     */
    public Date getLastModifiedTime() {
        return lastModifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSTAFF.LAST_MODIFIED_TIME
     *
     * @param lastModifiedTime the value for TSTAFF.LAST_MODIFIED_TIME
     *
     * @mbggenerated
     */
    public void setLastModifiedTime(Date lastModifiedTime) {
        this.lastModifiedTime = lastModifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSTAFF.LAST_MODIFIED_IP
     *
     * @return the value of TSTAFF.LAST_MODIFIED_IP
     *
     * @mbggenerated
     */
    public String getLastModifiedIp() {
        return lastModifiedIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSTAFF.LAST_MODIFIED_IP
     *
     * @param lastModifiedIp the value for TSTAFF.LAST_MODIFIED_IP
     *
     * @mbggenerated
     */
    public void setLastModifiedIp(String lastModifiedIp) {
        this.lastModifiedIp = lastModifiedIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSTAFF.VALID
     *
     * @return the value of TSTAFF.VALID
     *
     * @mbggenerated
     */
    public String getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSTAFF.VALID
     *
     * @param valid the value for TSTAFF.VALID
     *
     * @mbggenerated
     */
    public void setValid(String valid) {
        this.valid = valid;
    }
}