package com.jsy.cn.entity;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TUSER.PKID
     *
     * @mbggenerated
     */
    private Long pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TUSER.USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TUSER.USER_NAME
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TUSER.PASSWORD
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TUSER.REALM_ID
     *
     * @mbggenerated
     */
    private String realmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TUSER.STATUS
     *
     * @mbggenerated
     */
    private Long status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TUSER.VALID_START
     *
     * @mbggenerated
     */
    private Date validStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TUSER.VALID_END
     *
     * @mbggenerated
     */
    private Date validEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TUSER.VALID
     *
     * @mbggenerated
     */
    private String valid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TUSER.ADDED_BY
     *
     * @mbggenerated
     */
    private Long addedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TUSER.ADDED_NAME
     *
     * @mbggenerated
     */
    private String addedName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TUSER.ADDED_TIME
     *
     * @mbggenerated
     */
    private Date addedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TUSER.LAST_MODIFIED_BY
     *
     * @mbggenerated
     */
    private Long lastModifiedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TUSER.LAST_MODIFIED_NAME
     *
     * @mbggenerated
     */
    private String lastModifiedName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TUSER.LAST_MODIFIED_TIME
     *
     * @mbggenerated
     */
    private Date lastModifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TUSER.LAST_MODIFIED_IP
     *
     * @mbggenerated
     */
    private String lastModifiedIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TUSER.PKID
     *
     * @return the value of TUSER.PKID
     *
     * @mbggenerated
     */
    public Long getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TUSER.PKID
     *
     * @param pkid the value for TUSER.PKID
     *
     * @mbggenerated
     */
    public void setPkid(Long pkid) {
        this.pkid = pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TUSER.USER_ID
     *
     * @return the value of TUSER.USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TUSER.USER_ID
     *
     * @param userId the value for TUSER.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TUSER.USER_NAME
     *
     * @return the value of TUSER.USER_NAME
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TUSER.USER_NAME
     *
     * @param userName the value for TUSER.USER_NAME
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TUSER.PASSWORD
     *
     * @return the value of TUSER.PASSWORD
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TUSER.PASSWORD
     *
     * @param password the value for TUSER.PASSWORD
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TUSER.REALM_ID
     *
     * @return the value of TUSER.REALM_ID
     *
     * @mbggenerated
     */
    public String getRealmId() {
        return realmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TUSER.REALM_ID
     *
     * @param realmId the value for TUSER.REALM_ID
     *
     * @mbggenerated
     */
    public void setRealmId(String realmId) {
        this.realmId = realmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TUSER.STATUS
     *
     * @return the value of TUSER.STATUS
     *
     * @mbggenerated
     */
    public Long getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TUSER.STATUS
     *
     * @param status the value for TUSER.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Long status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TUSER.VALID_START
     *
     * @return the value of TUSER.VALID_START
     *
     * @mbggenerated
     */
    public Date getValidStart() {
        return validStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TUSER.VALID_START
     *
     * @param validStart the value for TUSER.VALID_START
     *
     * @mbggenerated
     */
    public void setValidStart(Date validStart) {
        this.validStart = validStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TUSER.VALID_END
     *
     * @return the value of TUSER.VALID_END
     *
     * @mbggenerated
     */
    public Date getValidEnd() {
        return validEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TUSER.VALID_END
     *
     * @param validEnd the value for TUSER.VALID_END
     *
     * @mbggenerated
     */
    public void setValidEnd(Date validEnd) {
        this.validEnd = validEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TUSER.VALID
     *
     * @return the value of TUSER.VALID
     *
     * @mbggenerated
     */
    public String getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TUSER.VALID
     *
     * @param valid the value for TUSER.VALID
     *
     * @mbggenerated
     */
    public void setValid(String valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TUSER.ADDED_BY
     *
     * @return the value of TUSER.ADDED_BY
     *
     * @mbggenerated
     */
    public Long getAddedBy() {
        return addedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TUSER.ADDED_BY
     *
     * @param addedBy the value for TUSER.ADDED_BY
     *
     * @mbggenerated
     */
    public void setAddedBy(Long addedBy) {
        this.addedBy = addedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TUSER.ADDED_NAME
     *
     * @return the value of TUSER.ADDED_NAME
     *
     * @mbggenerated
     */
    public String getAddedName() {
        return addedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TUSER.ADDED_NAME
     *
     * @param addedName the value for TUSER.ADDED_NAME
     *
     * @mbggenerated
     */
    public void setAddedName(String addedName) {
        this.addedName = addedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TUSER.ADDED_TIME
     *
     * @return the value of TUSER.ADDED_TIME
     *
     * @mbggenerated
     */
    public Date getAddedTime() {
        return addedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TUSER.ADDED_TIME
     *
     * @param addedTime the value for TUSER.ADDED_TIME
     *
     * @mbggenerated
     */
    public void setAddedTime(Date addedTime) {
        this.addedTime = addedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TUSER.LAST_MODIFIED_BY
     *
     * @return the value of TUSER.LAST_MODIFIED_BY
     *
     * @mbggenerated
     */
    public Long getLastModifiedBy() {
        return lastModifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TUSER.LAST_MODIFIED_BY
     *
     * @param lastModifiedBy the value for TUSER.LAST_MODIFIED_BY
     *
     * @mbggenerated
     */
    public void setLastModifiedBy(Long lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TUSER.LAST_MODIFIED_NAME
     *
     * @return the value of TUSER.LAST_MODIFIED_NAME
     *
     * @mbggenerated
     */
    public String getLastModifiedName() {
        return lastModifiedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TUSER.LAST_MODIFIED_NAME
     *
     * @param lastModifiedName the value for TUSER.LAST_MODIFIED_NAME
     *
     * @mbggenerated
     */
    public void setLastModifiedName(String lastModifiedName) {
        this.lastModifiedName = lastModifiedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TUSER.LAST_MODIFIED_TIME
     *
     * @return the value of TUSER.LAST_MODIFIED_TIME
     *
     * @mbggenerated
     */
    public Date getLastModifiedTime() {
        return lastModifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TUSER.LAST_MODIFIED_TIME
     *
     * @param lastModifiedTime the value for TUSER.LAST_MODIFIED_TIME
     *
     * @mbggenerated
     */
    public void setLastModifiedTime(Date lastModifiedTime) {
        this.lastModifiedTime = lastModifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TUSER.LAST_MODIFIED_IP
     *
     * @return the value of TUSER.LAST_MODIFIED_IP
     *
     * @mbggenerated
     */
    public String getLastModifiedIp() {
        return lastModifiedIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TUSER.LAST_MODIFIED_IP
     *
     * @param lastModifiedIp the value for TUSER.LAST_MODIFIED_IP
     *
     * @mbggenerated
     */
    public void setLastModifiedIp(String lastModifiedIp) {
        this.lastModifiedIp = lastModifiedIp;
    }
}